### ISSUE TITLE
FavIcon - The website needs a favicon!

### ISSUE THREAD

**Issue by ThorstenHans** [ThorstenHans/awesome-tech-conferences#9]
Currently the request for the ` favicon.ico` tanks with a `404` 😱  😄

**Comment by Rudy-Menekam** [comment]
Hello can i work on this issue

**Comment by ThorstenHans** [comment]
sure @Rudy-Menekam

**Comment by Rudy-Menekam** [comment]
Hello @ThorstenHans I have an issue running the app so i can't really test my changes
When I run the app I can't the following result on 1st image and why I insist I get a blank page
so I don't know if I am missing something
![Screenshot from 2022-10-21 11-12-24](https://user-images.githubusercontent.com/30177437/197180398-c03f948c-a377-47b1-8dca-d1dae5c2c30c.png)

**Comment by ThorstenHans** [comment]
Hmm, that's wired. Let me describe all the necessary steps to run the website locally

1. clone the repo
2. have the `hugo` CLI locally https://gohugo.io
3. have NodeJS installed locally
4. navigate to `./themes/conferences` 
5 run `npm i`
6. run either `npm run build` or `npm run watch` (compiles tailwindcss)
7 in the repository root folder run `hugo server`

**Comment by ThorstenHans** [comment]
Hey @Rudy-Menekam I've update docs and added a DevContainer to the repository. See `CONTRIBUTING.md` for further details.

**Comment by Rudy-Menekam** [comment]
Thanks @ThorstenHans 
will go through it

**Comment by ThorstenHans** [comment]
Added one by myself. Sorry @Rudy-Menekam
